apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - check_restaurant.py
          restartPolicy: OnFailure


# kubectl apply -f cronjob.yaml

# kubectl delete -f cronjob.yaml
#curl -sS https://webinstall.dev/k9s | bash
# k9s