---
apiVersion: v1  
kind: Pod
metadata:
  name: class1
spec:
  containers:
  - name: class1
    image: docker.io/nginx:1.14.2
  tolerations:
  - key: Gaming
    operator: Equal
    value: Approved
    effect: NoSchedule 
    
# kubectl apply --force -f pod.yaml
# kubectl delete -f pod.yaml 


#gke-cluster1-default-pool-3da02ca1-pl9t
# k drain gke-cluster1-default-pool-3da02ca1-pl9t --force  --ignore-daemonsets   --ignore-daemonsets