---
apiVersion: v1
kind: Namespace
metadata:
  name: statestreet
  labels:
    createdBy: "devops"

---
apiVersion: v1
kind: Namespace
metadata:
  name: chicagostreet
  labels:
    createdBy: "devops"




# kubectl apply  -f ns.yaml
# kubectl delete -f ns.yaml 