---
apiVersion: v1
kind: Namespace
metadata:
  name: statestreet
  labels:
    createdBy: "devops"
    demo: ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: lincolnstreet
  labels:
    createdBy: "devops"




# kubectl apply  -f ns.yaml
# kubectl delete -f ns.yaml 