# Declarative

---
apiVersion: v1  #v1beta1  v1alpha   v2 
kind: Pod
metadata:
  namespace: chicagostreet
  name: class1
  labels:
    createdBy: "devops"
  annotations:
    github: "https://github.com/moulayhafidelhafa/april-project-kuberntes"
    
spec:
  nodeSelector:
    node.kubernetes.io/instance-type: e2-medium
  containers:
  - name: class1
    image: docker.io/nginx:1.14.2
    ports:
    - containerPort: 80

---
apiVersion: v1  #v1beta1  v1alpha   v2 
kind: Pod
metadata:
  namespace: statestreet
  name: class1
  labels:
    createdBy: "devops"
  annotations:
    github: "https://github.com/moulayhafidelhafa/april-project-kuberntes"
spec:
  nodeSelector:
    node.kubernetes.io/instance-type: e2-medium
  containers:
  - name: class1
    image: docker.io/nginx:1.14.2
    ports:
    - containerPort: 80



# kubectl apply --force -f pod.yaml
# kubectl delete -f pod.yaml 




# kubectl apply --force -f pod.yaml
# kubectl delete -f pod.yaml 