---
apiVersion: v1
kind: Namespace
metadata:
  name: artemis


---  
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: artemis
  namespace: artemis
  labels:
    app.kubernetes.io/name: artemis
spec:
  replicas: 10
  selector:             # dictates how to find the pod
    matchLabels:
      app.kubernetes.io/name: artemis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: artemis    # assigns the label to the pod
    spec:
      containers:
      - name: artemis
        image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: artemis
  namespace: artemis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: artemis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# k apply -f clusterip.yaml
# k delete -f clusterip.yaml