apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  app_name: "MyApp"
  app_version: "1.0.0"
  log_level: "warning"


# k apply -f configmap.yaml
# k delete -f configmap.yaml


# k get cm 
