apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    kubernetes.io/change-cause: "version2"
spec:
  strategy: 
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
# k apply -f deploy.yaml 
# k delete -f deploy.yaml
# k get deploy
# k get deploy -o yaml 
# k describe deploy



# Downgrading/upgrading 

# See history 
# k rollout history deploy wordpress 
# k rollout history deploy wordpress   --revision NUMBER


# Carry out roll back
# k rollout  undo deploy wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



      #gcloud  container clusters  get-credentials  cluster-1  --zone  us-central1-c
      # gcloud config set project 