# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
  - name: sleepy
    image: alpine
    command: ['sleep', '10']  
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80


# k apply -f init.yaml

# k delete -f init.yaml