
---
apiVersion: v1
kind: Namespace
metadata:
  name: lincolnstreet
  labels:
    createdBy: "devops"
    
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: lincolnstreet
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 6
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl

#  kubectl apply -f rs.yaml
# kubectl delete -f rs.yaml        
