---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: lincolnstreet
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 6
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
        resources:
          requests:
            memory: "1G"
            cpu: "1"
          limits:
            memory: "2G"
            cpu: "2"

# k apply -f rs.yaml 
# k delete -f rs.yaml       
